name: Build wheels

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python setup.py sdist bdist_wheel
      - name: Store wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist

  publish:
    runs-on: ubuntu-latest

    needs: build
    if: github.ref_type == 'tag'

    steps:
      - name: Download wheel as artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheel-ubuntu-latest-3.10
          path: dist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
